include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    experimental_member_use: ignore
    invalid_annotation_target: ignore

linter:
  rules:
    avoid_unused_constructor_parameters: true # Неиспользуемые параметры конструктора
    avoid_void_async: true # async функции должны возвращать Future, а не void
    no_duplicate_case_values: true # Запрет дублирующихся case в switch
    prefer_null_aware_operators: true # Использовать ?., ?? для работы с null
    avoid_print: true # Не использовать print в production-коде
    await_only_futures: true # await можно использовать только с Future
    library_private_types_in_public_api: true # Не использовать закрытые типы в публичных API
    null_check_on_nullable_type_parameter: true # Проверка на null в nullable generic типах запрещена
    unrelated_type_equality_checks: true # Проверка на равенство разных типов
    void_checks: true # Проверка использования void значений
    secure_pubspec_urls: true # Только HTTPS-ссылки в pubspec.yaml
    prefer_const_literals_to_create_immutables: true # Использовать const для коллекций
    prefer_final_locals: true # Локальные переменные делать final
    curly_braces_in_flow_control_structures: true # Всегда фигурные скобки
    sort_constructors_first: true # Конструкторы в начале класса
    prefer_single_quotes: true # Использовать одинарные кавычки
    avoid_empty_else: true # Не использовать пустые else
    prefer_typing_uninitialized_variables: true # Типизировать неинициализированные переменные
    prefer_is_empty: true # Использовать isEmpty вместо length == 0
    prefer_is_not_empty: true # Использовать isNotEmpty вместо length > 0
    prefer_iterable_whereType: true # Использовать whereType вместо ручной фильтрации
    non_constant_identifier_names: true # Соблюдать правила именования
    camel_case_extensions: true # Имена extension в camelCase
    camel_case_types: true # Имена классов и enum в CamelCase
    file_names: true # Файлы — в lower_snake_case
    unintended_html_in_doc_comment: true # Не использовать HTML в doc-комментариях
    dangling_library_doc_comments: true # Doc-комментарии не должны быть потеряны
    library_annotations: true # Разрешены только допустимые аннотации библиотек
    provide_deprecation_message: true # Добавлять сообщение при @Deprecated
    type_literal_in_constant_pattern: true # Проверка типов в const pattern
    valid_regexps: true # Проверка корректности регулярных выражений
    prefer_const_constructors: true # Виджеты и объекты с const, если возможно
    use_key_in_widget_constructors: true # В конструкторы виджетов передавать Key
    avoid_redundant_argument_values: true # Не передавать дефолтные аргументы
    prefer_const_declarations: true # Использовать const для констант
    prefer_final_fields: true # Поля, которые не меняются, делать final
    avoid_private_typedef_functions: true # Не использовать приватные typedef в публичном API
    prefer_function_declarations_over_variables: true # Предпочитать декларации функций
    avoid_positional_boolean_parameters: true # Использовать именованные bool параметры
    avoid_relative_lib_imports: true # Избегать относительных импортов внутри lib/
    directives_ordering: true # Упорядочить импорты
    avoid_shadowing_type_parameters: true # Не перекрывать имена generic параметров
    avoid_types_as_parameter_names: true # Не использовать типы в качестве имён параметров
    collection_methods_unrelated_type: true # Проверка типов в методах коллекций
    depend_on_referenced_packages: true # Только используемые пакеты должны быть зависимостями
    hash_and_equals: true # Всегда переопределять hashCode при переопределении ==
    implicit_call_tearoffs: true # Явно использовать tear-offs
    no_wildcard_variable_uses: true # Не использовать `_` для хранения значений
    prefer_generic_function_type_aliases: true # Использовать generic typedef
    strict_top_level_inference: true # Строгая проверка типов на верхнем уровне
    unnecessary_overrides: true # Не переопределять без причины
    use_string_in_part_of_directives: true # Использовать строковые пути в part of
